language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
install: true
after_success: 
    deploy:
        provider: script
        script: scripts/deploy.sh
        on:
        branch: develop